apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: horizontal
  namespace: demo
spec:
  type: HorizontalScaling
  databaseRef:
    name: sh
  horizontalScaling:
    # replicas: 1
    shard:
      shards: 2
      replicas: 2
    hidden:
      replicas: 2
    configServer:
      replicas: 2