apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: horizontal
  namespace: demo
spec:
  type: HorizontalScaling
  databaseRef:
    name: mongo
  horizontalScaling:
    replicas: 3
    # shard:
    #   shards: 2
    #   replicas: 2
    hidden:
      replicas: 1
    # configServer:
    #   replicas: 2