apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: reconfigure
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: sh
  configuration:
    # replicaSet:
    #   configSecret:
    #     name: new-conf
    arbiter:
      configSecret:
        name: aconf
    hidden:
      configSecret:
        name: hconf
    shard:
      configSecret:
        name: rconf