apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: expansion
  namespace: demo
spec:
  type: VolumeExpansion  
  databaseRef:
    name: mongo
  volumeExpansion:
    replicaSet: 12Gi
    hidden: 13Gi
    mode: "Offline"