apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mongo
  namespace: demo
spec:
  version: "6.0.2"
  replicaSet:
    name: "replicaset"
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "300m"
          memory: "300Mi"
  replicas: 3
  # storageEngine: inMemory
  storageType: Durable
  storage:
    storageClassName: "standard"
    # storageClassName: linode-block-storage
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  # sslMode: requireSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: mongo-ca-issuer
  # clusterAuthMode: x509
  arbiter:
    podTemplate:
      spec:
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
  hidden:
    podTemplate:
      spec:
        resources:
          requests:
            cpu: "400m"
            memory: "400Mi"
    replicas: 2
    storage:
      storageClassName: "standard"
      # storageClassName: linode-block-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  # authSecret:
  #   name: hello
    # externallyManaged: true
  terminationPolicy: WipeOut
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 56790
        resources: {}
      serviceMonitor:
        interval: 10s
        labels:
          release: prometheus

