apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mongo
  namespace: demo
spec:
  #version: "6.0.2"
  version: "4.4.6"
  replicaSet:
    name: "replicaset"
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "300m"
          memory: "300Mi"
  replicas: 2
  # storageEngine: inMemory
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  # sslMode: requireSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: mongo-ca-issuer
  # clusterAuthMode: x509
  # arbiter:
  #   podTemplate:
  #     spec:
  #       resources:
  #         requests:
  #           cpu: "200m"
  #           memory: "200Mi"
  hidden:
    podTemplate:
      spec:
        resources:
          requests:
            cpu: "400m"
            memory: "400Mi"
    replicas: 2
    storage:
      storageClassName: "standard"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  # authSecret:
  #   name: hello
    # externallyManaged: true
  terminationPolicy: WipeOut
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     serviceMonitor:
  #       interval: 10s
  #       labels:
  #         release: prometheus
  #     exporter:
  #       args:
  #       - --collect.database
  #       env:
  #       - name: ENV_VARIABLE
  #         value: "yoo"
  #       resources:
  #         requests:
  #           memory: 444Mi
  #           cpu: 444m
  #         limits:
  #           memory: 444Mi
  #           cpu: 444m
  #       securityContext:
  #         runAsUser: 2000
  #         allowPrivilegeEscalation: false
  #       port: 56790

# str=0.32.0 val=0.32.0 ori=v0.32.0 meta= 
# image=kubedb/mongodb_exporter:v0.32.0@sha256:12c0d2f8c27a9747eba06cf623cbe5b7651cc6c7c9f48a2df16002eb4cd5d762 kubedb/mongodb_exporter:v0.32.0 
# tag=kubedb/mongodb_exporter:v0.32.0