apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mongo
  namespace: demo
spec:
  version: "4.2.3" #"4.4.6"
  replicaSet:
    name: "replicaset"
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "200m"
          memory: "200Mi"
  replicas: 2
  # storageEngine: inMemory
  storageType: Durable
  storage:
    # storageClassName: "longhorn"
    storageClassName: linode-block-storage
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 300Mi
  # sslMode: requireSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: mongo-ca-issuer
  # clusterAuthMode: x509
  arbiter:
    podTemplate:
      spec:
        resources:
          requests:
            cpu: "150m"
            memory: "150Mi"
  hidden:
    podTemplate:
      spec:
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
    replicas: 2
    storage:
      # storageClassName: "longhorn"
      storageClassName: linode-block-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 400Mi
  terminationPolicy: WipeOut