apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: sh
  namespace: demo
spec:
  version: "4.4.6"
  shardTopology:
    configServer:
      replicas: 3
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
      storage:
        resources:
          requests:
            storage: 100Mi
        storageClassName: standard
        # storageClassName: "linode-block-storage"
    mongos:
      replicas: 2
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
    shard:
      replicas: 2
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
      shards: 2
      storage:
        resources:
          requests:
            storage: 100Mi
        storageClassName: standard
  terminationPolicy: WipeOut
  arbiter:
    podTemplate:
      spec:
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
  hidden:
    podTemplate:
      spec:
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
    replicas: 1
    storage:
      storageClassName: "standard"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi