apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-09-21T11:16:10Z"
  generateName: rs-hidden-
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: rs
    app.kubernetes.io/managed-by: kubedb.com
    app.kubernetes.io/name: mongodbs.kubedb.com
    controller-revision-hash: rs-hidden-65cf596c
    mongodb.kubedb.com/node.type: hidden
    statefulset.kubernetes.io/pod-name: rs-hidden-0
  name: rs-hidden-0
  namespace: demo
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: rs-hidden
    uid: fb37a0ad-abbe-4130-b812-4daaac60453b
  resourceVersion: "83883"
  uid: 0f62cb28-3bff-432d-957f-30fb9b4d75b5
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: rs
              app.kubernetes.io/managed-by: kubedb.com
              app.kubernetes.io/name: mongodbs.kubedb.com
          namespaces:
          - demo
          topologyKey: kubernetes.io/hostname
        weight: 100
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: rs
              app.kubernetes.io/managed-by: kubedb.com
              app.kubernetes.io/name: mongodbs.kubedb.com
          namespaces:
          - demo
          topologyKey: failure-domain.beta.kubernetes.io/zone
        weight: 50
  containers:
  - args:
    - --dbpath=/data/db
    - --auth
    - --bind_ip_all
    - --port=27017
    - --ipv6
    - --tlsMode=requireTLS
    - --tlsCAFile=/var/run/mongodb/tls/ca.crt
    - --tlsCertificateKeyFile=/var/run/mongodb/tls/mongo.pem
    - --replSet=replicaset
    - --keyFile=/data/configdb/key.txt
    - --clusterAuthMode=x509
    command:
    - mongod
    env:
    - name: REPLICASET_DSN_ONLY_CORE
      value: replicaset/rs-0.rs-pods.demo.svc:27017,rs-1.rs-pods.demo.svc:27017,rs-2.rs-pods.demo.svc:27017
    - name: GOVERNING_SERVICE_NAME
      value: rs-pods
    - name: SHARD_TOPOLOGY_TYPE
      value: replica
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: REPLICA_SET
      value: replicaset
    - name: AUTH
      value: "true"
    - name: CLUSTER_AUTH_MODE
      value: x509
    - name: SSL_MODE
      value: requireSSL
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: rs-auth
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: rs-auth
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: percona/percona-server-mongodb:4.4.10
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/bash
          - -c
          - /init-scripts/hidden.sh
    livenessProbe:
      exec:
        command:
        - bash
        - -c
        - "set -x; if [[ $(mongo admin --host=localhost --tls --tlsCAFile=/var/run/mongodb/tls/ca.crt
          --tlsCertificateKeyFile=/var/run/mongodb/tls/client.pem --username=$MONGO_INITDB_ROOT_USERNAME
          --password=$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase=admin --quiet
          --eval \"db.adminCommand('ping').ok\" ) -eq \"1\" ]]; then \n          exit
          0\n        fi\n        exit 1"
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: mongodb
    ports:
    - containerPort: 27017
      name: db
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - bash
        - -c
        - "set -x; if [[ $(mongo admin --host=localhost --tls --tlsCAFile=/var/run/mongodb/tls/ca.crt
          --tlsCertificateKeyFile=/var/run/mongodb/tls/client.pem --username=$MONGO_INITDB_ROOT_USERNAME
          --password=$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase=admin --quiet
          --eval \"db.adminCommand('ping').ok\" ) -eq \"1\" ]]; then \n          exit
          0\n        fi\n        exit 1"
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 600Mi
      requests:
        cpu: 600m
        memory: 600Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /work-dir
      name: workdir
    - mountPath: /data/configdb
      name: config
    - mountPath: /init-scripts
      name: init-scripts
    - mountPath: /var/run/mongodb/tls
      name: certdir
    - mountPath: /data/db
      name: datadir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9vkqt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: rs-hidden-0
  initContainers:
  - args:
    - -c
    - "\n\t\t\techo \"running install.sh\"\n\t\t\t/scripts/install.sh"
    command:
    - /bin/sh
    env:
    - name: SSL_MODE
      value: requireSSL
    image: kubedb/mongodb-init:_linux_amd64
    imagePullPolicy: IfNotPresent
    name: copy-config
    resources:
      limits:
        memory: 300Mi
      requests:
        cpu: 300m
        memory: 300Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data/configdb
      name: config
    - mountPath: /init-scripts
      name: init-scripts
    - mountPath: /var/run/mongodb/tls
      name: certdir
    - mountPath: /client-cert
      name: client-cert
    - mountPath: /server-cert
      name: server-cert
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9vkqt
      readOnly: true
  nodeName: kind-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: rs
  serviceAccountName: rs
  subdomain: rs-pods
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: datadir
    persistentVolumeClaim:
      claimName: datadir-rs-hidden-0
  - emptyDir: {}
    name: config
  - emptyDir: {}
    name: init-scripts
  - emptyDir: {}
    name: certdir
  - name: client-cert
    secret:
      defaultMode: 256
      secretName: rs-client-cert
  - name: server-cert
    secret:
      defaultMode: 256
      secretName: rs-hidden-server-cert
  - emptyDir: {}
    name: workdir
  - name: kube-api-access-9vkqt
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-09-21T11:16:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-09-21T11:16:23Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-09-21T11:16:23Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-09-21T11:16:10Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://4e3f01254a75c8f3aa9336698479b0061448051cdb69721053a9d42c2aa25348
    image: docker.io/percona/percona-server-mongodb:4.4.10
    imageID: docker.io/percona/percona-server-mongodb@sha256:ea73a506fa02604660e3ef7d452d142a89587bb5daca15d3cc1b539a9b1000c5
    lastState: {}
    name: mongodb
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-09-21T11:16:11Z"
  hostIP: 172.18.0.2
  initContainerStatuses:
  - containerID: containerd://29a14fcab1ae95f71843dbc84ff44d17f5a89cdb989ff7b36410fd34897bc294
    image: docker.io/kubedb/mongodb-init:_linux_amd64
    imageID: docker.io/library/import-2022-09-19@sha256:109364caad08daed832c06d11604ad4c93fb5e93071e69620afa1a53f6993d1d
    lastState: {}
    name: copy-config
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://29a14fcab1ae95f71843dbc84ff44d17f5a89cdb989ff7b36410fd34897bc294
        exitCode: 0
        finishedAt: "2022-09-21T11:16:11Z"
        reason: Completed
        startedAt: "2022-09-21T11:16:11Z"
  phase: Running
  podIP: 10.244.0.49
  podIPs:
  - ip: 10.244.0.49
  qosClass: Burstable
  startTime: "2022-09-21T11:16:10Z"
